### ISSUE TITLE
Adjust casing in the README for clarity 

### ISSUE THREAD

**Issue by SpencerDawkins** [mjoras/SCONE-PROTOCL#1]
The README currently says 

> This is a respository containing artifacts related to the standardization efforts for "Securely Communicating Network Properties To Clients" (SCONE-PROTOCL), formerly known as SADCDN.

It should probably say 

> This is a **repository** containing artifacts related to the standardization efforts for "Securely **CO**mmunicating **NE**twork **PRO**perties **TO** **CL**ients" (SCONE-PROTOCL), formerly known as SADCDN.

Just to tie the acronym to the name a but more closely.

**Comment by mjoras** [comment]
This makes sense to do for clarity.

**Comment by SpencerDawkins** [comment]
I finally poked around to see whether the rules for working group acronyms has been updated since RFC 2418, and according to the datatracker, they are unchanged. From [Section 2.2:](https://datatracker.ietf.org/doc/html/rfc2418#autoid-6):

>    Working group name
>       A working group name should be reasonably descriptive or
>       identifiable. Additionally, the group shall define an acronym
>       **(maximum 8 printable ASCII characters)** to reference the group in
>       the IETF directories, mailing lists, and general documents.

Given this, I'll submit a PR with this text in the README, and we can discuss what the legal acronym should actually be, and Do The Right Thing. 

> This is a repository containing artifacts related to the standardization efforts for "Securely COmmunicating NEtwork PROperties to Clients" (SCONEPRO), formerly known as SADCDN.

**Of course, this change needs to ripple through other material for the BOF, so let's just change it once!**
