### ISSUE TITLE
Tighten up the definition of "network element(s)"

### ISSUE THREAD

**Issue by SpencerDawkins** [mjoras/SCONE-PROTOCL#103]
I'm still struggling with our use of the term "network element" (four times, and three are plural - "network elements"). My recollection is that we have a much tighter definition than (any) network element or network elements - the components I remember are that we're talking about one network element, that is

- In an access network
- May not be the first-hop network element, but can also do traffic shaping for flows that do not respect application limits
- Is a single network element (you can have many more than one network element in the access network, but the endpoint only accepts application limits from one network element).

Are there other attributes that I may not remember?

I'm not sure how much of this needs to be reflected in the charter, but some of it does. I'd bet we've all talked to people who wondered if this could happen more than once along the path, or wondered if you could do SCONEPRO with a core network (rather than an access network). At an absolute minimum 

> This work will define a way for an application to:
>
> 1. Signal their ability to receive application limits for UDP 5-tuples to **network elements**.
> 2. Receive notifications from **network elements** about the application limits for both upstream and downstream traffic.
> 3. Allow **network elements** to update the application limit as needed.

Should be "a network element" in every case. 

I'm happy to do a PR for this, and I self-assigned the issue, but I'd like feedback first.

**Comment by danwing** [comment]
Handling both a Wi-Fi access point (*) and cellular would be prohibited by charter if changed to "a network element", because "a" means "one".

(*) such as a "cellular hot spot" / "tethering" (which goes by many names)

**Comment by martinthomson** [comment]
My position here is that a network element is any *thing* that is in a position to drop packets that are sent on the path.  Any network element should have an equal ability to generate the signal.

**Comment by SpencerDawkins** [comment]
@danwing - so, you're injecting a bit of reality into the scope of the charter, which is not a bad thing, but it does go beyond most of the discussions I've been involved with. 

There was a significant amount of discussion in Zulip during the BOF about how this would work, and one key differentiator is whether the same CSP controls the WiFi access network and the cellular network - some do, others do not. 

If the same CSP controls both access networks, the CSP can provide application limits for both access networks in a knowledgeable way, I think. If that's not true, that sounds like the endpoint has two SCONEPRO sessions, one for each access network. Does that sound about right?

**Comment by SpencerDawkins** [comment]
@martinthomson - I agree with this. 

> My position here is that a network element is any _thing_ that is in a position to drop packets that are sent on the path. Any network element should have an equal ability to generate the signal.

If there are loads of network elements in the access network, I would think the plan would be that an endpoint talks to one network element. I don't think it would be super-manageable to have multiple (possibly differing) application limits for the same access network. Am I misunderstanding this?

**Comment by martinthomson** [comment]
The proposal that I'm working on (no chair hats, in case of doubt) let's every network element have a swing.  I think that is the only fair way to do this.

In practice, what you would do is reduce from a limit of infinite/unknown at the sender to whatever the first active network element wants, reducing further as the packet continues its journey.  In some cases, even if multiple network elements might want to say something, it might be that only one needs to say something.  Similarly, each might have to progressively reduce the limit.

**Comment by danwing** [comment]
Yes, the result is effectively application_bandwidth=min(element_1.application_bandwidth,element_2.application_bandwidth,element_3.application_bandwidth). The client or the network elements could do the minimization. There does not need to be coordination between the Wi-Fi and the cellular network; in fact, we don't want to require that!  Several scenarios where there is no coordination today but would be nice to have multiple network elements participating in application bandwidth signaling (e.g., laptop with 5G cellular that does Wi-Fi to other hosts).

**Comment by ihlar** [comment]
Agree with both Dan and Martin here. 
Anything other than allowing any on-path device to send information will lead to an overly complicated architecture.
 
I also agree that there should be no explicit coordination between network elements. Depending on the solution, the client either gets a single value that has been selected by the device closest to it, or it gets multiple values and does the minimization itself.

**Comment by SpencerDawkins** [comment]
> Agree with both Dan and Martin here. Anything other than allowing any on-path device to send information will lead to an overly complicated architecture.
> 
> I also agree that there should be no explicit coordination between network elements. Depending on the solution, the client either gets a single value that has been selected by the device closest to it, or it gets multiple values and does the minimization itself.

Yes, I agree with "no `EXPLICIT coordination between network elements". It might be helpful to have network elements communicating among themselves, but that can happen behind the scene. 

One question - I had assumed that we would end up with something like SUBSCRIBE/PUBLISH. I think we could make that work for an arbitrary number of network elements, but I wonder about how useful providing application limits from multiple network elements would be. If you get three different numbers, are you going to pick the minimum, or do something else? 

My understanding is that if one network element has a lower application limit, you probably want to believe that number. If you like another number better, but the lowest application-limit is accurate, you're taking a chance that assuming a higher application limit is taking a chance on triggering the ABR mechanisms that we're trying to avoid triggering.

**Comment by danwing** [comment]
> If you get three different numbers, are you going to pick the minimum, or do something else?

For troubleshooting it seems useful to know the various values. For example, is it the Wi-Fi creating the constraint or that the 5G hotspot is inside the building (rather than outside the building with better cellular signal).

**Comment by SpencerDawkins** [comment]
> > If you get three different numbers, are you going to pick the minimum, or do something else?
> 
> For troubleshooting it seems useful to know the various values. For example, is it the Wi-Fi creating the constraint or that the 5G hotspot is inside the building (rather than outside the building with better cellular signal).

That's fair. I'm wondering how stable this is when multiple network elements start changing the application limits at the same time, but let me start here. 

If a CSP is providing SCONEPRO application limits for a specific path through a specific access network, I'm not sure why different network elements controlled by a single CSP would be providing different application limits.

This sounds like it's headed towards providing traceroute functionality, but with application limits instead of the delay added by each individual network elements. Am I getting that wrong?

_(Translation from Spencer-speak - we can make this work, but I'm not sure why it's helpful to make it work)._

**Comment by danwing** [comment]
> If a CSP is providing SCONEPRO application limits for a specific path through a specific access network, I'm not sure why different network elements controlled by a single CSP would be providing different application limits.

Because each network element only knows what it knows?  

Another scenario:  A 5G 'hotspot' might provide both Ethernet (which someone uses for their laptop) and Wi-Fi, and it might by default favor the Ethernet user over the Wi-Fi users.  The cellular network does not know if the laptop or a smartphone is doing SCONEPRO (hidden by IPv4 NAT or obscured by IPv6 privacy addresses and IPv6 prefixes), but obviously the hotspot knows.

> This sounds like it's headed towards providing traceroute functionality, but with application limits instead of the delay added by each individual network elements. Am I getting that wrong?

That is building a technical solution. The v2 charter is now purposefully vague to defer all the difficult discussions to the working group.

But something traceroute-like could work and has advantage of proving the on-path device can modify packets, much like IETF justified ECN marking as proving the device could have easily dropped the packet (rather than ECN mark it).

**Comment by ihlar** [comment]
> That is building a technical solution. The v2 charter is now purposefully vague to defer all the difficult discussions to the working group.

+1 to this. No need to complicate the charter further. This is a great discussion for a working group.

**Comment by SpencerDawkins** [comment]
> > That is building a technical solution. The v2 charter is now purposefully vague to defer all the difficult discussions to the working group.
> 
> +1 to this. No need to complicate the charter further. This is a great discussion for a working group.

Hi, @ihlar, oh, I agree. And I'm already happy with the changes in #104. When @martinthomson and @fluffy get around to merging that PR, this issue should be closed.

I am wondering whether people are going to ask questions about the security aspects of getting application limits from any on-path network elements (and especially how a humble endpoint decides who to trust), but @martinthomson is much better at worrying about such things than I am. I just wanted to plant a seed in case we DO get those questions. The seed has been duly planted.:grinning:

**Comment by SpencerDawkins** [comment]
closed by #104
