### ISSUE TITLE
Suggested deliverables from a chartered SCONE working group

### ISSUE THREAD

**Issue by SpencerDawkins** [mjoras/SCONE-PROTOCL#11]
Strawman list

- Protocol specification for SCONE
- Use of SCONE for network-assisted video optimization through self-adaptation
- Applicability of SCONE protocol
- Manageability Guidance for SCONE protocol

**Comment by ihlar** [comment]
Perhaps this fits in the Applicability bucket but it would probably be good to have a deliverable on privacy requirements on any work that derives from the SCONE protocol specification.

**Comment by SpencerDawkins** [comment]
> Perhaps this fits in the Applicability bucket but it would probably be good to have a deliverable on privacy requirements on any work that derives from the SCONE protocol specification.

I agree, but I suspect that we would need that in the base SCONEPRO protocol specification. 

We could ask Zahed or a SEC AD, but I bet they ask us if we don't ask them. :wink:

**Comment by SpencerDawkins** [comment]
The question about privacy considerations is probably related to #6.

**Comment by SpencerDawkins** [comment]
We've had enough discussion in various venues asking what the difference between the various proposed deliverables deliverables might be, that I should go ahead and add descriptions (as I see the deliverables, and as a starting point) for each deliverable. And then we can talk about that in a way that people can track.
