### ISSUE TITLE
Separate signal for throughput advice

### ISSUE THREAD

**Issue by zaheduzzaman** [mjoras/SCONE-PROTOCL#110]
> 'separately signal' 
>https://github.com/mjoras/SCONE-PROTOCL/blob/803300e987a123d0f8c622b7ccebc5a5a3e532a0/documents/charter.md?plain=1#L21C13-L21C23

Separately from what? From the text above it is not clear if this is a separate signal to the network apart from media/data consumption request which usually goes to the server the client wants to connect.

**Comment by ihlar** [comment]
> Separately from what? From the text above it is not clear if this is a separate signal to the network apart from media/data consumption request which usually goes to the server the client wants to connect.

Separately from receiving throughput advice. So this point is about the need for any client initiated signaling at all. Perhaps the word 'separately' could simply be removed from the sentence.

**Comment by mjoras** [comment]
Yeah I believe this change was made by @martinthomson to try to clarify that both will be _considered_ separately by the working group.

**Comment by zaheduzzaman** [comment]
with the updated charter text this is no longer an issue. Thanks for addresing this in a nice way.
