### ISSUE TITLE
Different signals for 5-tuple or local path

### ISSUE THREAD

**Issue by ihlar** [mjoras/SCONE-PROTOCL#118]
This issue is based on an [email discussion](https://mailarchive.ietf.org/arch/msg/sadcdn/cmgQudfLJsjT2_u9WjT0B1rlpnI/).

Does the charter need to be explicit about that signals either apply to specific UDP 5-tuples or to a local path:

From the perspective of the client, this means it could potentially learn
either or both of these:
* Throughput advice for a particular 5-tuple
* Throughput advice for the local path

Does this require additional signaling and does the charter need to be explicit about it?

**Comment by chris-box** [comment]
Clients frequently have more than one 5-tuple active in the network at any one time. If I was a client application writer I think I would prefer to know whether the communicated advice is meant to cover all flows or just a particular one.

Granted, there are some common cases where there are multiple flows but one of them consumes 99.9% of the bytes. For such cases, this bit becomes less important. But my preference would be to also cater for applications with more than 1 flow of significant size (relative to the network's advice, which could be as low as 500kbps).

**Comment by fluffy** [comment]
Trying to summarize what I have heard on this

I have not seen a solution where the things stating the limit can prove that it can impact all the paths. Our security seems based on the idea that the device providing the limit can argue it can enforce that limit. I agree that often what is happening to a single 5-tuple is going to happen to everything. 

I would prefer to not expand the scope to include this problem because I think 1) the solutions we have seen so far did not solve this 2) the use cases we have discussed can be meant with the info only applying to a single 5 tuple.

**Comment by fluffy** [comment]
I think the PRs that just got merged made this clearer so I am going to close this.

**Comment by jsmith716** [comment]
I believe the value should define, or at least include the signal for, traffic limitation at the application flow level. This approach aligns with the goal of providing "explicit signaling between networks and applications" and offers a more accurate representation of network path limitations. Traffic can be managed per 5-tuple connection or per ABR application flow and focusing solely on individual 5-tuple flows could lead to misinterpretations of available bandwidth. For example, if a network path has a limit of 5 Mbps, an application using multiple 5-tuple connections might exceed this limit if each connection is treated separately. By signaling on the 5-tuple and being applied to the application flow level, it would provide clearer guidance that respects overall network path limitations. This would allow the ABR service to adjust across all their connections based on the network's recommendation – ensuring adherence to bandwidth constraints regardless of the number of individual 5-tuple flows, and accounting for the complexities of varying network policies (applied at bearer level or across individual flows).
