### ISSUE TITLE
Statement of applicability for SCONE

### ISSUE THREAD

**Issue by SpencerDawkins** [mjoras/SCONE-PROTOCL#12]
SCONE will make MUCH more sense if a service provider knows what customer is sending traffic. That shouldn't surprise anyone, but we need to write that down. Could be in a proposed charter deliverable, or in the charter, or in an applicability statement draft.

**Comment by SpencerDawkins** [comment]
> @SpencerDawkins and @mjoras : Since in the most recent commit to the charter we are adding an explicit deliverable (from the working group) around creating an applicability document for SCONE-PRO, what additional action if any do I need to take on this issue at this time?

I think the right answer, for now, is that we can defer action on this issue until we converge on the deliverables (and we haven't done that yet).

**Comment by SpencerDawkins** [comment]
I'm noting that the deliverables are being worked in PR #14 for Issue #11. If this discussion happens as part of discussion there, I'll link the PR to this issue.

**Comment by mjoras** [comment]
Closing for now, the charter includes this scope.
