### ISSUE TITLE
Transparent Rate Adaptation using Indications from Networks

### ISSUE THREAD

**Issue by martinthomson** [mjoras/SCONE-PROTOCL#20]
I like scones, but ...

![image](https://github.com/mjoras/SCONE-PROTOCL/assets/67641/8775cf88-a506-484d-abf6-c9d4c702b9fe)

**Comment by SpencerDawkins** [comment]
I like this one, but people keep making suggestions with pictures of scones, that look tasty. I'll tag this as for the charter, because we really should pick a name after the BOF that we can stick with ...

**Comment by SpencerDawkins** [comment]
@zaheduzzaman requested that we keep the name SCONEPRO through our (second)/(first workgroup-forming) BOF. If we charter for roughly what we requested as SCONEPRO, we'll keep the name, and if we charter for something significantly different, he asked that we pick a completely different name - and TRAIN is completely different from SCONEPRO.

**Comment by fluffy** [comment]
I do think we should consider what the name of the proposed WG should be.

**Comment by zaheduzzaman** [comment]
Yes, if not "sconepro" then lets pick another one... What are the proposals here?

**Comment by billwuqin** [comment]
Since the network properties to be communicated are only limited to upstream or downstream throughput, should we call "Simple communication from Network Elements (SCONE)".
Alternatively "Communication of Network prOperty to Endpoints (CANOE)" can be considered.

**Comment by chris-box** [comment]
I'd be happy with any name, but I generally prefer the Ronseal approach of "Does exactly what it says on the tin".

This leads me to Throughput Advice from Network Elements (TANE), or Network Element Throughput Advice (NETA).

**Comment by zaheduzzaman** [comment]
Thanks for the inputs. I think SCONE has been around for a while ( as part of SCONEPRO). Lets go with that.

**Comment by ihlar** [comment]
![image](https://github.com/user-attachments/assets/2c25b9a4-f10e-4c17-8f81-b417e904d59a)
