### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by martinthomson** [mjoras/SCONE-PROTOCL#21]
I would like to suggest that this be added as an explicit goal.  One of the biggest problems with current traffic shaping implementations is the lack of transparency -- and accountability -- regarding how they operate.  If we can't do better, I'd be surprised.

**Comment by Kevsy** [comment]
Fair point - do you mean in-band? e.g. a per-flow packet marking with an indication  that traffic shaping is active (or inactive).  And/or out-of-band, e.g. a published statement explaining how the traffic shaping operates.

In either case it would be useful to agree a definition of 'traffic shaping'. There are obvious ones ("TCP optimisers"/rate-limiters), but the radio scheduler on a best-effort cellular network could be (wrongly IMO) interpreted as traffic shaping. Same for an L4S-compliant network - although that 'shapes' how the network deals with the traffic, it's done so in collaboration with the endpoints.

**Comment by martinthomson** [comment]
I only care about whatever signal the network is sending to the client.

**Comment by martinthomson** [comment]
I should probably expand.  If the network is making a request of the client AND the client accedes to that request, then I want to ensure that this doesn't end up with the requests getting increasingly more preposterous or onerous.  It might be entirely reasonable or expected for a network to ask clients to limit their bandwidth usage to a certain limit.  But that can't mean creating a covert means of limiting it below what is agreed.

If this goes via a central point of control, in the OS or browser, I would expect to deploy a control that suppresses the signal, either completely or based on whether the request is considered acceptable.  So for instance, you might want to respect requests to drop usage below 5Mbps, but then ignore requests to reduce usage below 512Kbps, or have those invoke some exceptional indication (I don't want to go with notice and consent, but it's an option).

**Comment by Kevsy** [comment]
Thanks, understood and agree - I see this very much as a network hint rather than directive. So e.g. the network hints once regarding some context, and then leaves the application to decide if/what to do about it. Certainly the major video providers seem to well understand the correlation between the bitrate and the user experience - and I suspect it will be possible for them to determine if accounting for these network hints in ABR/congestion controls improves that experience, and under what conditions, and they decide what hints to use/ignore over time.

> But that can't mean creating a covert means of limiting it below what is agreed.

Agree. Being able to ignore the hint helps, as may a contract between  the application server and network.

**Comment by mjoras** [comment]
>  I see this very much as a network hint rather than directive. So e.g. the network hints once regarding some context, and then leaves the application to decide if/what to do about it.

@Kevsy I think we should be clear to some extent we expect the signalling here to go beyond "hints" in the normal sense. For example, one key benefit would be for the communication to take place and for the responsibility of achieving the ends of a network shaper to be moved to the content endpoints. In this situation the network would _disable_ the shaper in the network. This isn't just a hint to the endpoint to say "by the way, we are shaping you at this rate, good luck, have fun!". That would be useful, but ultimately not _that_ useful.

**Comment by SpencerDawkins** [comment]
Hi, @martinthomson,

> I would like to suggest that this be added as an explicit goal. One of the biggest problems with current traffic shaping implementations is the lack of transparency -- and accountability -- regarding how they operate. If we can't do better, I'd be surprised.

That's a helpful question to discuss, and sooner is better than later. 

There's been a bunch of helpful discussion on this issue, but I'd like to ask people to think about what "how shapers operate" means in practice. 

I can imagine a traffic shaper saying "your traffic has been shaped using the following parameters", "your traffic has been shaped using the following algorithm", or "your traffic has been shaped". 

There may be other levels of abstraction. What are people expecting to get as the result of transparency?

For what it's worth, AVTCORE burned a significant amount of time and energy getting the RTP over QUIC specification from "we should have a BCP for the Right Kind of Congestion Control/Rate Adaptation for RTP media" to "we should say 'use appropriate congestion control/rate adaptation for media". The current specification describes this in [Section 7](https://datatracker.ietf.org/doc/html/draft-ietf-avtcore-rtp-over-quic-07#name-congestion-control-and-rate), including subsections 7.1 to 7.4. (*)

If I look at SCONEPRO through that lens, 

(*) Video over RTP over QUIC isn't video over HTTP/3 over QUIC, but they're using the same underlying protocols, potentially the same implementations, and potentially the same network paths in the same operator networks.

**Comment by SpencerDawkins** [comment]
Re: hints versus requests versus commands - we had a lot of discussion about this in a transport-protocol context, as far back as the [second TRIGTRAN BOF at IETF 55 in 2002](https://www.ietf.org/proceedings/55/239.htm), and it wasn't a new issue then. 

The 20,000 meter summary from the TRIGTRAN BOF is basically 

- If a signal from something else is a hint, it can be ignored, but that means that you can send hints and see no difference in behavior, and if you're OK with having your hints ignored, maybe you don't need to send them?
- If a signal from something else is more than a hint, the entity receiving the signal has to defend itself from malicious (or just poorly implemented and configured) signal sources. 

TRIGTRAN would have been signaling using packets that aren't authenticated or integrity-protected. That's not what we're talking about in SCONEPRO, but **it would be good to think this history through, and make sure that we aren't missing anything that would justify objections.**

**Comment by martinthomson** [comment]
@SpencerDawkins,

> I can imagine a traffic shaper saying "your traffic has been shaped using the following parameters", "your traffic has been shaped using the following algorithm", or "your traffic has been shaped".

That sort of transparency would be useful (though not the last, which carries zero meaning), but I don't see this as the point of the effort.

This is about having application endpoints voluntarily take over shaping responsibilities.  So I would see this as the *application* saying "the network has asked me to shape as follows (varying degrees of detail according to UX needs and how the application complies with the request, if at all)".  That is, it would be specific and as detailed as necessary, not vague.

The TRIGTRAN outcome is relevant here, but I believe that the Internet has changed in a number of relevant ways in the interim.

**Comment by mirjak** [comment]
I would say the signal is basically "if you stay below the rate, I don't need to shape you (and I won't)". So if a client ignores the signal that is fine but it might eventually get shaped.


@martinthomson I don't understand your point that an OS or browser need to have any control here. Again, not providing this info to the client might lead to sharing anyway. Why would you suppress this information?

**Comment by martinthomson** [comment]
> "if you stay below the rate, I don't need to shape you (and I won't)"

Yep.

> @martinthomson I don't understand your point that an OS or browser need to have any control here. 

I'm thinking about the case where the network might overstep its bounds temporarily.  And so while you might ordinarily be OK with (for example) capping bandwidth usage at 1Mbps, you might find a request to cap at 56Kbps a bit too far.  In that case, you might want to do something other than comply.

If this is a possibility (and I would suggest that it would be if there weren't adequate transparency, as much as I think that networks generally try not to be awful to their customers), then I'd want a global control for this, not a per-application one.  In cases where the signal passes via a central point in the system (OS or browser), that is a logical point to apply some sort of compliance and notification policy.

**Comment by Kevsy** [comment]
>  This is about having application endpoints voluntarily take over shaping responsibilities. So I would see this as the application saying "the network has asked me to shape as follows (varying degrees of detail according to UX needs and how the application complies with the request, if at all)

Agree. And in turn the application would explicitly let the network know whether the request had been granted? That would help ensure no further network shaping.

**Comment by mirjak** [comment]
> If this is a possibility (and I would suggest that it would be if there weren't adequate transparency, as much as I think that networks generally try not to be awful to their customers), then I'd want a global control for this, not a per-application one. In cases where the signal passes via a central point in the system (OS or browser), that is a logical point to apply some sort of compliance and notification policy.

I'm not sure if I agree to this point of global control. Again an application can always decide to not comply (and it does today because it doesn't even have the information). If there is a way to suppress the information to the application, the OS or browser becomes effectively just a middlebox on the "path" that may complicate things when you want to change it.

I mean I would like to see that the OS implements this signal and provides an interface to the application, rather than each application implementing it separately. And then the OS would have control and visibility. However, I don't see that as a requirement. Actually transparency to the client (incl. what the OS is doing) is more important in my view.

**Comment by tmengKOP** [comment]
Agree with @mirjak . I feel like discussions till now aim at network properties associated with some given application. Per-application control may grant each application more flexibility. (On that front, an OS interface is helpful indeed though.)

Also, imho, the shaping rate by the network is usually not a kind of request to the application at least in current deployment. The application can of course choose not to comply, but the network will start to shape the traffic anyway once it goes beyond the shaping rate (e.g., which is determined by user's data plan).

**Comment by VMatrix1900** [comment]
Agree with @mirjak. The contract of speed throtlling is between the user and his CSP. Now SCONE is providing a way for the CAP and CSP to communicate about the contract. In this model, OS/Browser is just a middleman who is unaware of the SCONE, just like any random network device between the client and SCONE server. If OS/Browser gets the SCONE message first and preprocess the singal, how does application trust the OS/Browser to pass the "normal" SCONE singal without any modifcation? Introducing OS/Browser as the judge of the singal seems making it more complicated. Also as a third party, how does OS/Browser know CAP/CSP oversteps their bounds?

**Comment by britram** [comment]
This seems to reduce to the familiar question "what does 'on path' mean". Agree fully that transparency (in the sense of 'the end user or an agent thereof has access to all on-path signaling', not 'the endpoints are oblivious to the middleboxes', which is another meaning of the word 'transparency' in this context) should be a first-order goal called out in the charter.

**Comment by SpencerDawkins** [comment]
@atiwariphd - I agree with what you're saying here, and I want to think about how much of it should migrate into a charter PR. Do you want me to propose an update to the PR?
