### ISSUE TITLE
Assumptions on signaling per use cases

### ISSUE THREAD

**Issue by zaheduzzaman** [mjoras/SCONE-PROTOCL#22]
This need to be explained very well -

"it is not assumpted that all signaling use cases must or can be addressed by by the same protocol."

**Comment by SpencerDawkins** [comment]
@zaheduzzaman - we agree

**Comment by ihlar** [comment]
See PR #31 for an attempt to clarify this a bit more.

**Comment by SpencerDawkins** [comment]
closed by #31.
