### ISSUE TITLE
Drop the "Pro". Just "SCONE". It's cleaner.

### ISSUE THREAD

**Issue by britram** [mjoras/SCONE-PROTOCL#37]
Completely editorial and totally style-oriented feedback. The bug title says it all, but in addition to having a nicer potential logo, the "Properties" in the expansion is kind of redundant -- it's pretty clear in this scope that what's useful is property communication, not, say, addressing.

**Comment by SpencerDawkins** [comment]
Hi, @britram - I think I'm summarizing previous discussions correctly when I say that "SCONEPRO was better than SADCDN, and it at least conforms to the 8-character limit for WG abbreviations, but changing it to a better name would also be lovely". There's a suggestion in #20 for a lovely name. Whenever @martinthomson and @fluffy can schedule time with paint brushes and buckets, we should definitely talk!

**Comment by danwing** [comment]
<img width="649" alt="image" src="https://github.com/mjoras/SCONE-PROTOCL/assets/6002772/cd55bc76-b412-477d-8c83-253b28640052">

**Comment by SpencerDawkins** [comment]
> just need a pastry brush for the butter.

@danwing - DUDE! I'm on a DIET!! 

But seriously - @mjoras and I were pinged this week with questions from two guys in 3GPP SA4 with questions about "SCONE", so I hope we settle on a name Real Soon Now, if people in other SDOs are starting to pay attention. @martinthomson and @fluffy - that would be a distraction before IETF 119, I guess?

**Comment by martinthomson** [comment]
It's OK to have the BoF use one name and the working group another.  That happens all the time.  Let's not worry about the BoF name.

**Comment by SpencerDawkins** [comment]
I repeat that I do like the TRAIN name, but @britram AND @mjoras keep showing me pictures of scones, lobbying for that name. We kept SCONEPRO for the BOF, and I'm asking the folks with slides to make sure they use SCONEPRO instead of some variation, but we really should pick a name we should live with, after the BOF.

**Comment by SpencerDawkins** [comment]
Just to follow up on this - @zaheduzzaman asked that we keep the SCONEPRO name for a second BOF, just to minimize confusion, and if the proposed charter is significantly different after a second BOF, to change to a name that is completely different.
