### ISSUE TITLE
Clarify meaning of "video"?

### ISSUE THREAD

**Issue by britram** [mjoras/SCONE-PROTOCL#38]
From context, it's clear that "video traffic" means "videos sent from a server to a client via unicast", not other forms of "television replacement" such as multicast, nor bidirectional video communications such as videoconferencing. For an audience not steeped in the day to day of streaming or short video services, does it make sense to qualify this in the first paragraph?

**Comment by SpencerDawkins** [comment]
FWIW, I had a side conversation with @mjoras a week or two ago, about whether SCONE is "video" or "media", where "media" might include things like immersive images. I didn't ask the question then, but if we're drilling down on "video", maybe I should ask the question now.

**Comment by ihlar** [comment]
We can use media or video, but the important properties (imo) are:
1) Sent / streamed from a server to a client via unicast
2) Supports media bitrate adaptation.

**Comment by SpencerDawkins** [comment]
@britram, @mjoras, and @ihlar - I think we Did The Right Thing by leaving this as "video" for the BOF, but I do think we should discuss making the change AFTER the BOF. 

The properties @ihlar listed, just as a starter, would cover a lot more than "segment-by-segment-style video", if you can figure out how to request segment-by-segment for the media of your choice.

**Comment by mjoras** [comment]
Closing for now, video is the most understandable least contentious way to phrase this. We already say things like QUIC connections and ABR.
