### ISSUE TITLE
Provide a minimal SCONEPRO architecture

### ISSUE THREAD

**Issue by mjoras** [mjoras/SCONE-PROTOCL#4]
This is from discussion at the side meeting. For example, does the charter need to be very explicit about a "minimal" acceptable architecture, with a diagram showing a mobile client application communicating with a network device?

**Comment by SpencerDawkins** [comment]
Is this just an ASCII diagram, or text, or ... I can take a shot at this, and we will review the PR before committing

**Comment by mjoras** [comment]
Yeah, I think ASCII diagram makes the most sense, and we'll go from there.

**Comment by SpencerDawkins** [comment]
@mjoras - I may start with a different .md file that contains the ASCII diagram and text. I hope we don't need to include diagrams in the charter, but we do need to have SOMETHING in mind, no matter where diagrams end up. It will be good to have a starting point that everyone has at least seen, especially for presenters at the BOF.

**Comment by SpencerDawkins** [comment]
The more I think about this, the more I think the architecture goes in a document (not needed for the charter), but it will be useful to have a set of terms we can use in the charter to describe the actors that make use of the protocol.

**Comment by SpencerDawkins** [comment]
I'd definitely like to get feedback on the minimal reference architecture in #27, but I don't think we need to put it IN the charter. I'll rearrange the labels accordingly.

**Comment by mjoras** [comment]
Closing for now we can revisit later if needed.
