### ISSUE TITLE
Identity disclosure - Flow identity, who initiates SCONEPRO

### ISSUE THREAD

**Issue by mjoras** [mjoras/SCONE-PROTOCL#6]
This is somewhat related to https://github.com/mjoras/SCONE-PROTOCL/issues/5

That is, is there any incumbent requirement on the device/standardized mechanism that requires it identifying itself? Or should the standardized protocol not require any sort of identity disclosure?

My opinion is that it does not need to require any disclosure, as the service provider can use its own mechanisms to make any associations it needs to, without explicitly asking for that identity from the client.

**Comment by anooptomar29** [comment]
Yes I agree @mjoras. Idea is to leverage the flow/traffic detection done by CSPs (which they currently do for their video policy implementation and for some other reasons such as metering, charging etc). So we don't need to do any thing additional for identifying the flow/user.

**Comment by ihlar** [comment]
I agree that there is little value in mandating that the client identifies itself as a particular application. On the other hand, it would be very nice outcome if the use of this protocol would let us get rid of solutions based on SNI-sniffing and similar (when it's not needed for other reasons). Some kind traffic category indication could perhaps be an alternative here?

**Comment by SpencerDawkins** [comment]
> I agree that there is little value in mandating that the client identifies itself as a particular application. On the other hand, it would be very nice outcome if the use of this protocol would let us get rid of solutions based on SNI-sniffing and similar (when it's not needed for other reasons). Some kind traffic category indication could perhaps be an alternative here?

I agree with @ihlar that this would be a very nice outcome, but I'm basing what follows on my understanding of the history of IETF proposals in this space. .

- "would be nice", or even "would be very nice", goals in an initial BOF request invite commenters to focus on these nice/very nice goals, and distract from MUST HAVE goals that the BOF proponents and supporting BOF community base their support on. If a BOF has more than one goal, all of the goals share fate - so a "would be nice" goal can delay, or even be be fatal to, efforts to charter work toward a MUST HAVE goal.
- If we do get a lot of support for a traffic category indication in discussions, and it looks like this would be MUST HAVE for these supporters, adding it later might be fine, but 
- even with a lot of community support, we will need comments from the IETF SEC community that also support this addition, or (more likely) at least explain whether, and in which circumstances, work that accomplishes this goal is likely to be approved by the IETF community at Last Call time. Late surprises are the worst.

**Comment by SpencerDawkins** [comment]
Just to follow up on my previous comment, if we want to add anything like a traffic category indication, we should be extremely aware of past IETF efforts in this space. 

@britram mentioned the [PLUS BOF at IETF 96](https://www.ietf.org/proceedings/96/plus.html) in a previous side meeting call, I was the responsible AD, and @mirjak had just joined the IESG at the previous IETF meeting, so was still quite involved as a proponent. Any of us can explain what happened there, in more detail than the minutes provide. 

Or, just take my word for it, that the PLUS BOF experience was horrible. :cursing_face: :skull_and_crossbones:

**Comment by mirjak** [comment]
We don't really need application identification but we need some indication that a client would like to use this service and get input from the network node. The network will then provide the information but also monitor the respective flow that it follows the network guidance.

Alternative we could also provide the network guidance pro-actively, however, then you have to monitor all and we then still need a mechanism to identify applications that may be candidates for shaping in case of congestion (when sending more than the indicated rate).

So, having a way for the client to explicitly request the service would that make things slightly easier.

**Comment by SpencerDawkins** [comment]
> So, having a way for the client to explicitly request the service would that make things slightly easier.

YES, YES, YES!!! @mirjak, thank you for spotting this. That improves scalability (unless all endpoints want to use SCONEPRO), and using an opt-in model ought to make SCONEPRO more palatable for anyone who has concerns about interactions with middleboxes (of whatever flavor). 

There may be more reasons to have clients explicitly request the service, but those two are sufficient for me to agree.

**Comment by anooptomar29** [comment]
@mirjak The main reason for not adding this as a requirement is to minimize the additional work to be done by CSPs and rather leverage the existing mechanism to identify the flow. The way we are visualizing this feature is as follows; 
1. CSPs would continue to use existing mechanism (whether it is SNI detection in initial client hello HTTP handshake message or some other mechanism)  
2.  Whenever CSPs see a need to communicate with CAPs w.r.t specific flow to configure flow specific parameters CSPs would use SCONE-PRO mechanism to communicate the same. 

This way CSPs can continue to use their existing mechanism to detect the flows and they don't need to add support for new detection mechanism. 
However I do understand your point also as this would make detection mechanism standard across CAPs and CSPs but we need to discuss the implication of adding this requirement as it may interact with ECH like features in future.

**Comment by mirjak** [comment]
No sure if we want to restrict ourselves that way already or if need further discussion about this point?

**Comment by SpencerDawkins** [comment]
@anooptomar29,

> I think we need further discussion on this. For extreme clarity listing the points to be discussed ;
> 
> 1. Nothing additional is required from client OR
> 2. Client needs to share some indication to n/w device that a client would like to use this (SCONE-PRO) service for this specific flow OR
> 3. Client needs to share its capability w.r.t support for (SCONE-PRO)  with n/w device
> 
> @mirjak @ihlar It may help if we can come-up with some example call flow to explain what is needed from client and at what point in time client needs to share the same. This may help in clarifying point about bidirectional or unidirectional ( n/w to client only) .

I definitely agree on an example call flow being useful. [I just put a VERY sketchy example as a comment in another issue](https://github.com/mjoras/SCONE-PROTOCL/issues/21#issuecomment-1919221981).

I should probably add an issue to come up with an example call flow.
