### ISSUE TITLE
How would the network element be discovered and authenticated?

### ISSUE THREAD

**Issue by SpencerDawkins** [mjoras/SCONE-PROTOCL#65]
We do say client-initiated in the charter, but we don't address discovery (yet).

First question - is discovery in scope? We think it needs to be, because we have proprietary solutions now, and discovery would be needed for a complete standardized solution.

**Comment by fluffy** [comment]
Following

**Comment by SpencerDawkins** [comment]
Now that we have added deliverables to the charter, I propose this issue should be addressed in the "SCONEPRO protocol" deliverable.

**Comment by mjoras** [comment]
This is largely a property of the solution. Some solutions will not require a discovery phase while others do. I think the it is therefore implicitly in scope insofar as any solution requiring it would have to define it.

The same goes for authentication. If it is deemed by the WG that the signal needs authentication properties, it must provide provisions to do so.
