### ISSUE TITLE
How would the signal be propagated?  How would it be protected?

### ISSUE THREAD

**Issue by SpencerDawkins** [mjoras/SCONE-PROTOCL#66]
In the charter this would be stated as a Property, not solved in the charter.

**Comment by fluffy** [comment]
Following

**Comment by SpencerDawkins** [comment]
The charter talks about protection now, the question is about propagation (so, how this works with browsers, etc.)

**Comment by SpencerDawkins** [comment]
Now that we have added deliverables to the charter, I propose this issue should be addressed in the "Network Properties for Streaming Video" deliverable.

**Comment by mjoras** [comment]
This is addressed in the two different solution sketch drafts we have so far.
