### ISSUE TITLE
What are the privacy properties of the signal? 

### ISSUE THREAD

**Issue by SpencerDawkins** [mjoras/SCONE-PROTOCL#67]
If making the signal available to applications is the goal, does that have unwanted properties?

This is related to questions from the BOF about the implications of entirely encrypted channels being available between endpoints and network elements (and from PLUS).

**Comment by danwing** [comment]
The privacy concern is the other way around:  from the user's device to the ISP.  Such as:  is the application name disclosed to the ISP?  Is the server name disclosed to the ISP (contravening TLS encrypted SNI)?  Is the specific video disclosed to the ISP ("watch the new $moviename without consuming your monthly bandwidth!", "the government asked the ISP to disclose if you're watching the video of last week's protest").

**Comment by ihlar** [comment]
@danwing those are valid concerns, but there are concerns in both directions I believe, e.g., can the network expose unique user identities to the application (e.g., MSISDN), the type of subscription the user has, user location.. and what does that mean for user privacy?

**Comment by SpencerDawkins** [comment]
Now that we have added deliverables to the charter, I propose this issue should be addressed in the "SCONEPRO protocol" deliverable.

**Comment by mjoras** [comment]
Discussed at end in draft-tomar-sconepro-privacy-02.
