### ISSUE TITLE
Could this be used to violate or undermine things like network neutrality protections for network users?

### ISSUE THREAD

**Issue by SpencerDawkins** [mjoras/SCONE-PROTOCL#68]
Net neutrality comes in many flavors, and has many different definitions. The potential for combinatorial explosion are limitless. 

We don't see existing architectural guidance about this from the IETF, the IESG, or the IAB at this point.

**Comment by jlivingood** [comment]
> We don't see existing architectural guidance about this from the IETF, the IESG, or the IAB at this point.

There are many things the IETF does based on all sorts of requirements and there is a feedback loop from the market (incl regulatory environment) to the standards process. To use one example, the IETF previously held a P2Pi workshop on similar issues, see RFC 5594 - https://www.rfc-editor.org/rfc/rfc5594.html. That workshop - borne from a NN issue - drove the creation of LEDBAT, CDNI, and other WGs over time. It has arguably had influence on new congestion control AQMs and the development of dual queue networking in TSVWG. 

So I don't think we can claim the IETF has not, does not, or should not consider these things. 

Rather - why not take it on directly, and add a section on the NN rule implications in many markets (EU, UK, US, Canada, etc.)?

**Comment by jlivingood** [comment]
> My interpretation of the wording is that traffic management is an action by the network operator to directly affect a flow of traffic within its network. Although that is allowed with certain conditions (ref: Article 3(3) second subparagraph: reasonable traffic management) , I believe that SCONE would not fall under the definition of traffic management since it is a hint rather than an action. I.e., it would not breach Net Neutrality, and could be offered to all content providers (non-discriminatory).

Seems reasonable. And I think some of the presentations we heard suggest to me that any SCONE hint provided from the network was about not a *desired* bitrate limit but an *actual* bitrate limit. So the hint is less a hint than a statement of network policy IMO. That may stregthen @Kevsy's point of view above.

**Comment by ihlar** [comment]
See https://datatracker.ietf.org/doc/draft-tan-sconepro-netneutrality/ for extended discussion.

**Comment by bryantanwc** [comment]
In the draft listed by @ihlar , I have made reference to the BEREC guidelines (EU) and internet society document 2015 (for US and other markets).  The intent of aforementioned draft   is not to frame it as a written statement verifying compliance with net neutrality – but instead to frame it around the goal of ensuring, through collaborative stakeholder input in the WG, that the proposed technical solution stays consistent with net neutrality principles as outlined, in various markets

**Comment by SpencerDawkins** [comment]
Now that we have added deliverables to the charter, I propose this issue should be addressed in the "SCONEPRO protocol" deliverable.

**Comment by mjoras** [comment]
Discussed at end in draft-tan-sconepro-netneutrality-00
