### ISSUE TITLE
Incentives for usage as designed/intended?

### ISSUE THREAD

**Issue by SpencerDawkins** [mjoras/SCONE-PROTOCL#70]
How much do we need to say about the potential for damage, gaming the system, etc.?

Can the signal be designed so that there is no incentive to fake it, like with ECN?

**Comment by SpencerDawkins** [comment]
This does build on the advisory nature of SCONEPRO.

**Comment by mjoras** [comment]
Addressed in draft-tomar-sconepro-ecn-01
