### ISSUE TITLE
Throughput, not bandwidth

### ISSUE THREAD

**Issue by Kevsy** [mjoras/SCONE-PROTOCL#77]
The charter mentions:

"communicating network properties to clients relevant to a given application, such as the **maximum achievable bandwidth** for a video"

"a solution that communicates the **maximum achievable bandwidth** for a video"

I believe we should change 'maximum achievable bandwidth'  to 'maximum achievable throughput' because:

1- bandwidth _is_ maximum achievable throughput. Hence the current wording reads as  'maximum achievable maximum achievable throughput' 
2- 'bandwidth' is used in spectrum allocation, and that is a relevant factor in how a radio network delivers video - so there is a risk of confusion  between the two contexts.
3- the second paragraph of the charter starts  with "Local mobile radio conditions may constrain the maximum throughput", so replacing bandwidth with throughput later in the document maintains consistency.

**Comment by SpencerDawkins** [comment]
> The charter mentions:
> 
> "communicating network properties to clients relevant to a given application, such as the **maximum achievable bandwidth** for a video"
> 
> "a solution that communicates the **maximum achievable bandwidth** for a video"
> 
> I believe we should change 'maximum achievable bandwidth' to 'maximum achievable throughput' because:
> 
> 1- bandwidth _is_ maximum achievable throughput. Hence the current wording reads as 'maximum achievable maximum achievable throughput' 2- 'bandwidth' is used in spectrum allocation, and that is a relevant factor in how a radio network delivers video - so there is a risk of confusion between the two contexts. 3- the second paragraph of the charter starts with "Local mobile radio conditions may constrain the maximum throughput", so replacing bandwidth with throughput later in the document maintains consistency.

@Kevsy, thank you for entering this as its own issue. IMO, we've had a LOT of conversations in various places (dating back to SADCDN) between 

- "Clients using SCONEPRO can intelligently respond to changes in achievable BANDWIDTH - especially over cellular RAN links with fluctuating signal strength", and 
- "Clients using SCONEPRO can intelligently choose the highest achievable rung on an ABR video ladder, ensuring the best possible QoE"

Your suggestion points us MORE clearly toward the second point of view, without constraining the charter so tightly that non-ABR video would be out of scope. I think that's the right thing to do. 

I think this issue
