### ISSUE TITLE
What does available bitrate mean

### ISSUE THREAD

**Issue by fluffy** [mjoras/SCONE-PROTOCL#89]
Is it peak, average, something else. How do we talk about this and express it ?

**Comment by fluffy** [comment]
Zahed had some ideas on having charter say the WG will figure that out.

**Comment by zaheduzzaman** [comment]
I would say we let the WG agree on what the "available bitrate" means and define a protocol to sent that information to the client . I would suggest to update the charter as below - 

>The Secure Communication of Network Properties (SCONEPRO) Working Group's primary objective is to define "maximum achievable throughput" for a streaming video service and specify an on-path protocol for securely communicating that network attribute to the clients.

**Comment by ihlar** [comment]
@zaheduzzaman please check #94 I tried to convey what you wrote with some small edits.

**Comment by SpencerDawkins** [comment]
Closed by #94
