### ISSUE TITLE
Don't overly specify mobile access.

### ISSUE THREAD

**Issue by mjoras** [mjoras/SCONE-PROTOCL#91]
While mobile is a pressing use case these problems are not unique to mobile access technology, and the charter should reflect that.

**Comment by ihlar** [comment]
#92 is an attempt at addressing this.

**Comment by jlivingood** [comment]
> While mobile is a pressing use case these problems are not unique to mobile access technology, and the charter should reflect that.

Especially since 70-90% of "mobile" bits are actually carried over WiFi networks.
