### ISSUE TITLE
(editorial) remove the bulleted list in the WG scope/focus text

### ISSUE THREAD

**Issue by zaheduzzaman** [mjoras/SCONE-PROTOCL#95]
As this is the only bullet list item, lets remove the list and make it part of the paragraph above. Also consider it we are repeating the same informaiton twice in these lines.

https://github.com/mjoras/SCONE-PROTOCL/blob/70488d8cfaeb67c5d098ac2fc177a88a0ab7fcdb/documents/charter.md?plain=1#L20

**Comment by ihlar** [comment]
Addressed in #96.
